## Exercise 5.A NumPy fundamentals

# This files contains exercises to learn basics of NumPy

In [ ]:
pip install numpy as np

In [1]:
import numpy as np

## Array Basics

In [2]:
#Create a standard Python list with the variable name fruits, containing the values apple, banana, cherry, and date

fruits = ["apple", "banana", "cherry", "date"]

In [3]:
#Create a variable named arr_1 as a one-dimensional array containing fruits then print arr_1.
arr_1 = np.array(fruits)
print(arr_1)


['apple' 'banana' 'cherry' 'date']


In [ ]:
#Write an expression to check the data type of values contained in arr_1. 
# After you run the cell, add a comment to explain what data type is returned. 
# For the dtype, what does the letter mean, and what does the number mean?

print(arr_1.dtype)

## 'U' stands for Unicode string (text data)
# '6' is the length of the longest string in the array ('banana' and 'cherry' are 6 chars)
# NumPy sets the dtype to fit the longest value in the array
# Summary> all the data in this array is stored as text upto 6 characters.

<U6


In [ ]:
#5d
arr_2 = np.array([(10,11,12),(13,14,15)])
print(arr_2)
#The double brackets indicate it's 2-dimensional.each inner set of brackets is one row.

[[10 11 12]
 [13 14 15]]


In [6]:
#5e
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [ ]:
#5e
#Checking if the array changed
print(arr_2)
#transpose .T doesn't change the original array it just shows it transposed.(dimensions swapped 2x3 becomes 3x2)

[[10 11 12]
 [13 14 15]]


In [8]:
#5f
arr_3 = np.array([(1,3,5),(2,4,6)])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [ ]:
#5g
arr_4 = np.array([arr_3[0,2], arr_3[1,1]])
print(arr_4)

[5 4]


In [11]:
#5h
arr_5 = np.array([(1,1),(1,1),(1,1)])
print(arr_5)

#I also saw that np.ones method can be used here as a shortcut.

[[1 1]
 [1 1]
 [1 1]]
