# Exercise 1.B NumPy Random 


In [2]:
import numpy as np

 ## Generating Random Numbers

In [25]:
r_1 = np.random.randint(1,20,size=2)
print(r_1)

[7 5]


In [4]:
r_2 = np.random.randint(1,20,(1,2))
print(r_2)

[[19 14]]


In [5]:
r_3 = np.random.rand(2,1)
print(r_3)

[[0.317118  ]
 [0.92631073]]


In [8]:
r_4 = np.random.randint(20,100,(4,5))
print(r_4)

[[73 76 56 33 53]
 [83 63 49 30 61]
 [32 85 57 66 51]
 [97 53 54 94 86]]


In [9]:
r_5 = np.random.rand(4,5)
print(r_5)

[[0.44627148 0.46816021 0.52045845 0.47388241 0.58583299]
 [0.32786839 0.24233212 0.7913325  0.16642198 0.2163534 ]
 [0.55414938 0.59429084 0.76259035 0.53754032 0.95552306]
 [0.58911703 0.56028784 0.93317631 0.70145322 0.54055378]]


 ## Generating Random Choices from an Array

In [11]:
students = np.array(['Longley', 'Maritza', 'Rodas', 'Jessica', 'Eyerusalem', 'Mina', 'Godknows', 'Jimmy', 'Paul', 'Will', 'Sultan', 'Cagla'])

In [12]:
call_on = np.random.choice(students,1)
print(call_on)

['Jessica']


In [16]:
breakout_groups = np.random.choice(students, (3,4))
print(breakout_groups)
#It wouldn't be a good way to create breakout rooms because the array contains 12 elements and we need to pick 12 random elements.
#It is almost impossible to create a list with unique names. We need to decrease the amount of selection or increase the number of sample amount
#Also same name can be in two different groups this is also not logical for this operation.

[['Cagla' 'Mina' 'Eyerusalem' 'Eyerusalem']
 ['Jessica' 'Jimmy' 'Jessica' 'Mina']
 ['Mina' 'Mina' 'Mina' 'Maritza']]


In [28]:
call_on_weighted = np.random.choice(students, 5, p=[0.3, 0.0, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07, 0.07])
print(call_on_weighted)
#I gave 30% and %0 possibility in p values as question was asking from me. I just seperated the rest of the 
# 70% of the possibility equally between rest of the 10 students

['Sultan' 'Rodas' 'Longley' 'Sultan' 'Paul']


 ## Generating a Normal Distribution

In [29]:
bell_curve=np.random.normal(10,5,(4,5))
print(bell_curve)

[[ 6.16666374  8.59808454  8.03656174 11.75445117 11.91256273]
 [ 9.04939537 10.32361219 12.31619999  4.90129855 11.5795947 ]
 [ 9.47100891 21.59089361 13.83289438  4.99710087 20.78573312]
 [ 4.47142405 11.26126086  8.08444601 13.81618557  0.77658104]]
