# Exercise 1.C Performing operations on arrays 


In [24]:
import numpy as np

## Simple arrays

In [25]:
r_1 = np.random.randint(1, 20, size=2)
r_2 = np.random.randint(1, 20, size=(1, 2))
r_3 = np.random.random(size=(2, 1))
r_4 = np.random.randint(20, 100, size=(4, 5))
r_5 = np.random.random(size=(4, 5))

## Permutations

In [26]:
print(r_4)

[[74 52 62 81 84]
 [27 45 90 57 70]
 [61 33 82 74 60]
 [65 58 56 89 57]]


In [27]:
np.random.shuffle(r_4)
print(r_4)

[[61 33 82 74 60]
 [65 58 56 89 57]
 [74 52 62 81 84]
 [27 45 90 57 70]]


### Shuffle changed the order of the rows but didn't change the elements inside the rows.

In [28]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)
""" print(r_4) """ #shuffle changed the original array while permutation gave a new changed array.

[[61 33 82 74 60]
 [74 52 62 81 84]
 [27 45 90 57 70]
 [65 58 56 89 57]]


' print(r_4) '

I would use shuffle if i don't need the original array later on
I would use permutation if i will need the original array.

 ## Mathematical Operations

In [29]:
print(r_1)
print(r_2)
print(r_1.shape)
print(r_2.shape)
print(np.add(r_1,r_2))

[5 9]
[[17  1]]
(2,)
(1, 2)
[[22 10]]


In [30]:
print(r_1)
print(r_3)
print(r_1.shape)
print(r_3.shape)
print(np.add(r_1,r_3))

[5 9]
[[0.48096382]
 [0.57515597]]
(2,)
(2, 1)
[[5.48096382 9.48096382]
 [5.57515597 9.57515597]]


In [34]:
print(r_2)
print(r_4)
print(r_2.shape)
print(r_4.shape)
print(np.add(r_2,r_4))
#This doesnt work because number of columns must be same. r_2 has 2 columns and r_4 has 5.

[[17  1]]
[[61 33 82 74 60]
 [65 58 56 89 57]
 [74 52 62 81 84]
 [27 45 90 57 70]]
(1, 2)
(4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [38]:
print(r_1.shape)
print(r_4.shape) 
#Adding these array together would't work because number of columns are not equal
print(np.add(r_1, r_4))

(2,)
(4, 5)


ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [41]:
np.add(np.array([1]),r_4)
#One element array can be added to any other array"""


array([[62, 34, 83, 75, 61],
       [66, 59, 57, 90, 58],
       [75, 53, 63, 82, 85],
       [28, 46, 91, 58, 71]])

In [42]:
np.add(np.array([[1]]),r_4)
# It works even if it is 2d

array([[62, 34, 83, 75, 61],
       [66, 59, 57, 90, 58],
       [75, 53, 63, 82, 85],
       [28, 46, 91, 58, 71]])

In [ ]:
np.add(np.array([1,1,1,1,1]), r_4)
#This works too because column numbers are equal to element number of a 1D array

array([[62, 34, 83, 75, 61],
       [66, 59, 57, 90, 58],
       [75, 53, 63, 82, 85],
       [28, 46, 91, 58, 71]])

In [45]:
np.add(np.array([[1],[1]]), r_4)
#This didn't work becase 2x1 array can't be added to a 4x5 array 

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

Column numbers must be equal for .add to work. It adds the values of one array to other array based on columns
It can work if one of the arrays has only one element. It adds that element to all other elements of the other array.

## Rounding.

In [49]:
print(r_3)

[[0.48096382]
 [0.57515597]]


In [51]:
np.trunc(r_3)

array([[0.],
       [0.]])

In [ ]:
np.fix(r_3)
##np.fix is deprecated, np.trunc is preferred


array([[0.],
       [0.]])

In [53]:
np.floor(r_3)

array([[0.],
       [0.]])

In [54]:
np.ceil(r_3)

array([[1.],
       [1.]])

In [55]:
np.round(r_3, 2)

array([[0.48],
       [0.58]])

## Cumulative Operations

In [56]:
print(r_4)

[[61 33 82 74 60]
 [65 58 56 89 57]
 [74 52 62 81 84]
 [27 45 90 57 70]]


In [57]:
np.sum(r_4)

np.int64(1277)

In [59]:
np.sum(r_4, axis=0) #sum of the columns

array([227, 188, 290, 301, 271])

In [60]:
np.sum(r_4, axis=1) #sum of the rows

array([310, 325, 353, 289])

In [ ]:
np.cumsum(r_4) #it starts from first row moves towards right and jumps to second rows and goes on..

array([  61,   94,  176,  250,  310,  375,  433,  489,  578,  635,  709,
        761,  823,  904,  988, 1015, 1060, 1150, 1207, 1277])

In [ ]:
np.cumsum(r_4, axis=0) # cumsum of each column top to bottom

array([[ 61,  33,  82,  74,  60],
       [126,  91, 138, 163, 117],
       [200, 143, 200, 244, 201],
       [227, 188, 290, 301, 271]])

## Grocery Problem

In [68]:
bag1 = np.array([2,3,4,0])
bag2 = np.array([4,0,1,2])
print(bag1)
print(bag2)

[2 3 4 0]
[4 0 1 2]


In [69]:
print(f'The first bag contains {np.sum(bag1)} items, and the second bag contains {np.sum(bag2)} items.')

The first bag contains 9 items, and the second bag contains 7 items.


In [79]:
totals = np.vstack((bag1,bag2))
print(totals)
totals_cat = np.sum(totals, axis=0)
print(f'There are {totals_cat[0]} vegetables, {totals_cat[1]} fruits, {totals_cat[2]}, boxes of snacks, and {totals_cat[3]} beverages in the two grocery bags.')


[[2 3 4 0]
 [4 0 1 2]]
There are 6 vegetables, 3 fruits, 5, boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [80]:
# Ali reported knocking on 5 doors on Monday, 4 on Tuesday, 6 on Wednesday, 4 on 
# Thursday, and 2 on Friday. Create a variable holding an array of these values. 
ali = np.array([5,4,6,4,2])

In [81]:
# Ben missed Monday because he was out of town. He reported knocking on 5 on 
# Tuesday, 5 on Wednesday, 3 on Thursday, and 4 on Friday. Create a variable holding 
# an array of Ben’s values.
ben= np.array([0,5,5,3,4])

In [86]:
#Carla reported knocking on 3 doors on Monday, 6 on Tuesday, 3 on Thursday, and 4 
#on Friday. She was sick on Wednesday so missed that day. Create a variable 
#holding an array of Carla’s values
carla = np.array([3,6,0,3,4])

In [ ]:
""" totarr = np.vstack([ali,ben,carla])
print(totarr)
total_knocks = np.sum(totarr)
print(total_knocks)
potential_votes = total_knocks / 2
print(potential_votes) """
totarr = np.vstack([ali,ben,carla]) # merged the arrays verticaly
print(totarr)
total_knocks = (np.sum(totarr,axis=1)) # total knocked per person 
print(total_knocks)
total_group = np.sum(totarr) # total as a group
print(total_group)
daily_total = np.cumsum(totarr, axis=0) # doors knocked daily as a group
print([daily_total[-1]])
potential_votes = daily_total / 2 # Daily potential votes
print(potential_votes)
pot_total = np.sum(potential_votes) # Total potential votes
print(pot_total)




[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]
[21 17 16]
54
[array([ 8, 15, 11, 10, 10])]
[[2.5 2.  3.  2.  1. ]
 [2.5 4.5 5.5 3.5 3. ]
 [4.  7.5 5.5 5.  5. ]]
56.5
