# Exercise 1.A NumPy: Manipulating Arrays  


In [29]:
import numpy as np

 ## Looping Through Arrays

∗ In a new code cell, create a variable named arrA as a two-dimensional array 
containing (11, 12, 13) and (14, 15, 16) then print arrA. 

In [30]:
arrA = np.array([[11,12,13],[14,15,16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


∗  In a new code cell, loop through the first dimension of arrA (i.e. for x in arrA) and 
print each element multiplied by 2.

In [31]:
for x in arrA:
    print(x*2)

[22 24 26]
[28 30 32]


∗ In a new code cell, loop through the second dimension of arrA (i.e. for y in x) and 
print each element multiplied by 2.

In [32]:
for x in arrA:
    for y in x:
        print(y*2)

22
24
26
28
30
32


Comments: When i only used one loop for x it only checked the first dimension which mean 2 elements between brackets. and multiplied the content in these elements
Second loop went in to that elements and now we are in the second dimension. When we multiply in the print statement, it multiplied all the elements one by one unlike the first print statement.
First print statement multiplied the element by 2 that is why the result included the brackets.

Add another code cell. Again loop through the second dimension of arrA (i.e. for y 
in x), but this time, assign x*2 to a variable named loop_result. Add another line 
of code to print loop_result, then add a comment to the cell to explain how/why 
this result is different.

In [33]:
""" for x in arrA:
    for y in x:
        loop_result = x*2
        print(loop_result) """
        
""" for x in arrA:
    for y in x:
        loop_result = x*2
print(loop_result) """

for x in arrA:
    for y in x:
        loop_result = x*2
    print(loop_result)

[22 24 26]
[28 30 32]


Comment: My first try is commented out. Since i left the print(loop_result) inside the loop every time y is checked in x the result is printed. 
I took the print statement out of the loop and i only multiplied the first dimension of the x.
Then i left it in the first loop only. I saw the multiplied results for both dimensions.

## Joining and Stacking Arrays

In [34]:
joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [35]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [36]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [ ]:
stacked_array_2 = np.stack((joined_array_1,joined_array_2), axis=2)

#This is not working because shapes are different, we need same shaped array to be able to stack them

In [37]:
another_joined_array = np.concatenate((joined_array_1,arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [40]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)

#The shape doesn't have to be exactly same to concatenate, bu the shape of the joining axis should be same.
#So, if we are concatenate on axis 1 number of rows should be same. if we conc. on axis 0 number of columns should be same.


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [46]:
newarr1=np.hstack((arrA,arrA))
#[[11 12 13 11 12 13]
# [14 15 16 14 15 16]]
#Hstack stacks the arrays side by side.(horizon), so number of rows stay same. array grows to the right with added column
newarr2=np.dstack((arrA,arrA))
#[[[11 11]
#  [12 12]
#  [13 13]]
#
# [[14 14]
#  [15 15]
#  [16 16]]]
#dstack is like putting to arrays on top of each other so it adds a 3rd dimension. And it groups the elements in the same indexes
newarr3=np.vstack((arrA,arrA))
print(newarr2)
#[[11 12 13]
# [14 15 16]
# [11 12 13]
# [14 15 16]]
#Vstack stacks the array vertically, so array is added under the other one. So numbe rof columns stay same but number of rows increased.

[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


 ## Splitting Arrays

In [ ]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

#joined_array_1 was 4x3 2D array. It is splitted into two equal parts from so became 2x3,2x3 two array appeared
#They both have 2 dimesions.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [49]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)
#This one also splitted from rows, but this time they are not equal. first array is 2x3 and the other two is 1x3
#They are all still 2D but their shape is different

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [52]:
result_1=np.where(arrA % 2 ==0, 'even', 'odd')
print(result_1)

[['odd' 'even' 'odd']
 ['even' 'odd' 'even']]


## Sorting and Filtering Arrays

In [58]:
arrB = np.array([(7,6),(13,5),(7,3)])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [69]:
print(arrB)
z = arrB<7
arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [71]:
y = arrB >= 7
arrD = arrB[y]
print(arrD)

[ 7 13  7]
